# Render Blueprint: deploy API (Node/Express) + Client (React static site)
#
# Usage:
# - Push this repo to GitHub
# - In Render: New → Blueprint → select repo → Apply
# - After first deploy finishes, set the missing env vars marked with `sync: false`.

services:
  # ================================================
  # Single Web Service: API + serves React build
  # ================================================
  - type: web
    name: form-builder
    env: node
    autoDeploy: true
    buildCommand: npm ci && cd client && npm ci && npm run build
    startCommand: node server/index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production

# Notes:
# - This blueprint deploys a single web service. The server serves /api/* and
#   also serves the React app from client/build for all non-API routes.
# - Set env vars with `sync: false` in the Render dashboard after creation.

